- platform: LinkedIn
  url: "https://www.linkedin.com/company/jrhealthins/"
# - platform: Facebook
#   url: "https://facebook.com/jrhealthins"
- platform: Yelp
  url: "https://www.yelp.com/biz/j-and-r-health-insurance-puyallup"
